export type View =
  | 'products'
  | 'addProduct'
  | 'detailsProduct'
  | 'editProduct'
  | 'listProducts'
  | 'deleteProduct'
  | 'addProducer'
  | 'detailsProducer'
  | 'editProducer'
  | 'listProducers'
  | 'deleteProducer'
  | 'addCategory'
  | 'detailsCategory'
  | 'editCategory'
  | 'listCategory'
  | 'deleteCategory';
